[package]
authors     = ["Jan Kościsz <koscis.j@gmail.com>"]
categories  = ["command-line-utilities", "development-tools"]
description = "Format Rust macro attributes across multiple lines"
edition     = "2024"
keywords    = ["cargo", "development-tools", "formatting", "macro"]
license     = "MIT"
name        = "cargo-macrofmt"
repository  = "https://github.com/kostekIV/cargo-macrofmt"
version     = "0.0.2"

[lib]
name = "cargo_macrofmt"
path = "src/lib.rs"

[[bin]]
name = "cargo-macrofmt"
path = "src/main.rs"

[dependencies]
anyhow      = { version = "1" }
clap        = { version = "4", features = ["derive"] }
proc-macro2 = { version = "1.0.103", features = ["span-locations"] }
serde       = { version = "1", features = ["derive"] }
similar     = { version = "2.7.0" }
syn         = { version = "2.0.111", features = ["extra-traits", "full", "visit"] }
toml        = { version = "0.9.8" }
toml_edit   = { version = "0.23.9" }
walkdir     = { version = "2.5" }
